name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  cs-check:
    name: "Lint: (php-cs-fixer)"
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: OskarStark/php-cs-fixer-ga@2.18.0
        with:
          args: --dry-run --diff --config=.php_cs


